import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainView: {
        // flex: 1,
        // alignItems: 'center',
    },
    mainScrollView: {
        // flexGrow: 1,
        // justifyContent: 'center',
        alignItems: 'center',
    },
    headerImage: {
        width: '100%',
        height: 180,
        resizeMode: 'contain',
        marginTop: 0,
        // opacity: 0.6,
        marginBottom: 20,
        // borderRadius: 5,
    },
    headerContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 40,
        fontWeight: 'bold',
        color: 'white',
        textShadowColor: 'black',
        textShadowOffset: {width: 2, height: 2},
        textShadowRadius: 30,
    },
    touchableView: {
        marginBottom: 30,
        width: 300,
        height: 50,
        alignItems: "center",
        backgroundColor: "green",
        borderWidth: 3,
        borderRadius: 10,
    },
    touchableText: {
        textAlign: "center",
        paddingTop: 7,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    button: {
        backgroundColor: "blue",
        padding: 20,
        borderRadius: 5,
        margin: 5,
    },
    buttonText: {
        fontSize: 20,
        color: "#fff",
    },
    itemContainer: {
        display: "flex",
        marginVertical: 16,
        paddingTop: 20,
        paddingBottom: 10,
        // paddingHorizontal: 24,
        marginHorizontal: 24,
		// borderBottomColor: 'rgb(176, 196, 222)',
		// borderBottomWidth: StyleSheet.hairlineWidth,
        borderWidth: 5,
    },
    itemTitle: {
        // display: "flex",
        flex: 1,
        marginTop: 12,
        marginBottom: 6,
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        textAlign: 'center',
    },
    itemTitleGreen: {
        fontSize: 24,
        fontWeight: '600',
        color: 'green',
    },
    itemDescription: {
        // display: "flex",
        flex: 1,
        margin: 6,
        fontSize: 14,
        fontWeight: '400',
        color: 'black',
        textAlign: 'center',
    },
    itemDescriptionBold: {
        marginTop: 8,
        fontSize: 18,
        fontWeight: 'bold',
        color: 'black',
    },
    itemImage: {
        // width: '100%',
        height: 220,
        width: 260,
        resizeMode: 'cover',
        borderRadius: 5,
    },
    footerImage: {
        width: 75,
        height: 75,
        resizeMode: 'cover',
        borderRadius: 5,
    },
    footerContainer: {
        paddingVertical: 24,
        paddingHorizontal: 24,
    },
    detailPage: {
        display: "flex",
        paddingHorizontal: 24,
    },
    detailContainer: {
        marginVertical: 20,
        paddingVertical: 20,
        borderWidth: 5,
    },
    detailTitle: {
        // display: "flex",
        // flex: 1,
        marginBottom: 6,
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        textAlign: 'center',
    },
    detailDescription: {
        // display: "flex",
        flex: 1,
        // margin: 8,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'center',
    },
    detailDescriptionLeft: {
        flex: 1,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'left',
    },
    detailDescriptionRight: {
        flex: 1,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'right',
    },
    detailImage: {
        height: 200,
        width: 260,
        // width: '100%',
        // padding: 20,
        // resizeMode: 'cover',
        borderRadius: 5,
    },
    thumbnailContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        marginHorizontal: 14,
    },
    thumbnail: {
        width: 70,
        height: 60,
        resizeMode: 'cover',
        margin: 6,
        borderRadius: 5,
        borderColor: 'lightsalmon',
    },
    imageContainer: {
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
    },
	spinner: {
		flex: 3,
        marginTop: 20,
		marginHorizontal: 10,
		minWidth: 60,
	},
    cartButton: {
        flex: 5,
        marginTop: 20,
        marginHorizontal: 10,
        // width: 80,
        height: 50,
        alignItems: "center",
        backgroundColor: "green",
        borderWidth: 2,
        borderRadius: 10,
    },
});

export default styles;
