import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainView: {
        flex: 1,
        // alignItems: 'center',
    },
    mainScrollView: {
        // flexGrow: 1,
        // justifyContent: 'center',
        alignItems: 'center',
    },
    touchableView: {
        marginBottom: 30,
        width: 300,
        height: 50,
        alignItems: "center",
        backgroundColor: "green",
        borderWidth: 3,
        borderRadius: 10,
    },
    touchableText: {
        textAlign: "center",
        paddingTop: 7,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    button: {
        backgroundColor: "blue",
        padding: 20,
        borderRadius: 5,
        margin: 5,
    },
    buttonText: {
        fontSize: 20,
        color: "#fff",
    },
    sectionContainer: {
        display: "flex",
        marginTop: 32,
        paddingHorizontal: 24,
		borderBottomColor: 'rgb(176, 196, 222)',
		borderBottomWidth: StyleSheet.hairlineWidth,
    },
    sectionTitle: {
        // display: "flex",
        flex: 1,
        marginTop: 12,
        marginBottom: 6,
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        textAlign: 'center',
    },
    sectionTitleGreen: {
        fontSize: 24,
        fontWeight: '600',
        color: 'green',
    },
    sectionDescription: {
        // display: "flex",
        flex: 1,
        margin: 6,
        fontSize: 14,
        fontWeight: '400',
        color: 'black',
        textAlign: 'center',
    },
    sectionDescriptionBold: {
        marginTop: 8,
        fontSize: 18,
        fontWeight: 'bold',
        color: 'black',
    },
    sectionImage: {
        // width: '100%',
        height: 220,
        width: 260,
        resizeMode: 'cover',
        borderRadius: 5,
    },
    headerContainer: {
        paddingHorizontal: 24,
        marginBottom: 10,
        backgroundColor: 'lightsalmon',
        borderRadius: 6,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        textAlign: 'center',
    },
    headerImage: {
        width: '100%',
        height: 150,
        resizeMode: 'contain',
        opacity: 0.6,
        marginBottom: 20,
        // borderRadius: 5,
    },
    footerImage: {
        width: 75,
        height: 75,
        resizeMode: 'cover',
        borderRadius: 5,
    },
    footerContainer: {
        marginTop: 32,
        paddingHorizontal: 24,
        marginBottom: 40,
    },
    detailContainer: {
        display: "flex",
        // marginTop: 32,
        paddingHorizontal: 24,
		borderBottomColor: 'rgb(176, 196, 222)',
		borderBottomWidth: StyleSheet.hairlineWidth,
    },
    detailTitle: {
        // display: "flex",
        // flex: 1,
        marginTop: 18,
        marginBottom: 6,
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        textAlign: 'center',
    },
    detailDescription: {
        // display: "flex",
        flex: 1,
        // margin: 8,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'center',
    },
    detailDescriptionLeft: {
        flex: 1,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'left',
    },
    detailDescriptionRight: {
        flex: 1,
        fontSize: 16,
        fontWeight: '400',
        color: 'black',
        paddingHorizontal: 16,
        paddingVertical: 10,
        textAlign: 'right',
    },
    detailImage: {
        height: 200,
        width: 260,
        // width: '100%',
        // padding: 20,
        // resizeMode: 'cover',
        borderRadius: 5,
    },
    thumbnailContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        marginHorizontal: 14,
    },
    thumbnail: {
        width: 70,
        height: 60,
        resizeMode: 'cover',
        margin: 6,
        borderRadius: 5,
        borderColor: 'lightsalmon',
    },
    imageContainer: {
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
    },
	spinner: {
		flex: 3,
        marginTop: 20,
		marginRight: 10,
		minWidth: 60,
	},
    cartButton: {
        flex: 5,
        marginTop: 20,
        marginHorizontal: 10,
        // width: 80,
        height: 50,
        alignItems: "center",
        backgroundColor: "green",
        borderWidth: 2,
        borderRadius: 10,
    },
});

export default styles;
